name: build-graphene-os

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container: 
      image: ubuntu:22.04
      
    timeout-minutes: 360

    steps:
      - name: Include sbin in PATH
        run: export PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin
        
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update
          apt install -y repo yarnpkg zip rsync python3 git gnupg

      - name: Download source code (dev branch)
        run: |
          mkdir grapheneos-14
          cd grapheneos-14
          repo init -u https://github.com/GrapheneOS/platform_manifest.git -b 14
          repo sync -j8
          
      - name: Build GrapheneOS
        run: |
          source build/envsetup.sh
          # target x64 Android emulator
          lunch sdk_phone64_x86_64-cur-user
          # build default target (as recommended for emulator builds)
          m
