name: build-graphene-os

on:
  push:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    container: 
      image: kylemanna/aosp
    
    steps:
      - name: test
        run: |
          ls
          mkdir test
